### ISSUE TITLE
Read only typelibray attribute values in Mimir 

### ISSUE THREAD

**Issue by atorjusen** [mimir-org/mimir#143]
Refer to: [https://github.com/mimir-org/typelibrary/issues/291](https://github.com/mimir-org/typelibrary/issues/291) 

Since we use libraryattributes fetched form PCA in the mimir model, the properites of these attributes should be read-only in Mimir.

![image](https://user-images.githubusercontent.com/19664830/204521105-f1cc03b5-d0a2-42a8-a571-57cee6e0973e.png)

This applies to these attributes: 
          specifiedScope
          specifiedProvenance
          rangeSpecifying
          regularitySpecified

The value 1250 as shown above whould be editable, and it should be possible to selct form the list of units of measure. 

So the image in the inspector panel should show the correct value for these attributes, and they should be read only in this gui.

**Comment by reliaboe** [comment]
This is resolved by another feature and solution
