### ISSUE TITLE
Off-Page nodes arent connecting between Child/Parent

### ISSUE THREAD

**Issue by Arjunch00** [mimir-org/mimir#8]
How to actually connect the incomming and outgoing transports of the Oil Sperator system with the new transports going in to the pump system @Arjunch00 

![Image](https://user-images.githubusercontent.com/79528819/186646437-297269b5-ff79-4f22-9a5d-e29b3a173d37.png)

**Comment by Arjunch00** [comment]
NOTES AS A BACKLOG TASK: This task is High-Priority - but there isnt enough time or resources to start this fix.

**Comment by reliaboe** [comment]
Offpage nodes is removed and implemented in another way. Closing this issue.
